spring:
  application:
    name: shortify
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/shortify
    username: user
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: 'create-drop'

server:
  shutdown: graceful